"""
┌─────────────────────────────────────────────────────────────────────┐
│  📄 llama_factory_yaml.py                                           │
│  Module: cy_exec.training.llama_factory_yaml                        │
│  Role: Strict LLaMA Factory YAML import/export owned by Yield.       │
│  模块职责：Yield 拥有的 LLaMA Factory YAML 严格导入导出；未知字段报错。    │
└─────────────────────────────────────────────────────────────────────┘
"""

from __future__ import annotations

from typing import Any

import yaml
from pydantic import ValidationError

from .product_models import LlamaFactoryPrefill, TrainingParameters

# Only these LLaMA Factory fields are mapped to the canonical TrainingSpec.
# 只有这些 LLaMA Factory 字段会映射到规范 TrainingSpec。
# Anything else fails closed; silent ignoring would change training intent.
# 其余字段一律 fail closed；静默忽略会改变训练意图。
ALLOWED_FIELDS = frozenset(
    {
        "model_name_or_path",
        "dataset",
        "num_train_epochs",
        "max_steps",
        "learning_rate",
        "lora_rank",
        "lora_alpha",
        "lora_dropout",
        "per_device_train_batch_size",
        "gradient_accumulation_steps",
        "cutoff_len",
        "template",
    }
)


class LlamaFactoryYamlError(ValueError):
    """Typed YAML mapping failure carrying a stable Product code.

    携带稳定 Product 错误码的有类型 YAML 映射错误。
    """

    def __init__(self, code: str, detail: str) -> None:
        super().__init__(f"{code}: {detail}")
        self.code = code


def parse_llama_factory_yaml(text: str) -> LlamaFactoryPrefill:
    """Map a LLaMA Factory YAML document onto canonical parameters.

    未知字段、类型错误或越界值都以稳定错误码失败，不会被静默忽略。
    """

    if not isinstance(text, str) or not text.strip():
        raise LlamaFactoryYamlError("YIELD_LLAMA_FACTORY_YAML_REQUIRED", "the YAML body is empty")
    try:
        document = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise LlamaFactoryYamlError("YIELD_LLAMA_FACTORY_YAML_INVALID", f"cannot parse YAML: {exc}") from exc
    if not isinstance(document, dict):
        raise LlamaFactoryYamlError(
            "YIELD_LLAMA_FACTORY_YAML_INVALID", "the YAML document must be a mapping"
        )
    unknown = sorted(str(key) for key in document if str(key) not in ALLOWED_FIELDS)
    if unknown:
        raise LlamaFactoryYamlError(
            "YIELD_LLAMA_FACTORY_UNKNOWN_FIELD",
            "unsupported fields: " + ", ".join(unknown),
        )

    model_name = _optional_text(document.get("model_name_or_path"), "model_name_or_path")
    dataset = _optional_text(document.get("dataset"), "dataset")
    try:
        parameters = TrainingParameters(
            epochs=document.get("num_train_epochs", 1),
            max_steps=document.get("max_steps"),
            per_device_batch_size=document.get("per_device_train_batch_size", 1),
            gradient_accumulation_steps=document.get("gradient_accumulation_steps", 1),
            learning_rate=document.get("learning_rate", 0.0002),
            max_sequence_length=document.get("cutoff_len", 512),
            lora_rank=document.get("lora_rank", 8),
            lora_alpha=document.get("lora_alpha", 16),
            lora_dropout=document.get("lora_dropout", 0.05),
            template=document.get("template", "default"),
        )
    except ValidationError as exc:
        raise LlamaFactoryYamlError(
            "YIELD_LLAMA_FACTORY_INVALID_VALUE", _validation_detail(exc)
        ) from exc
    return LlamaFactoryPrefill(
        model_name_or_path=model_name,
        dataset=dataset,
        parameters=parameters,
    )


def render_llama_factory_yaml(
    *,
    model_name_or_path: str | None,
    dataset: str | None,
    parameters: TrainingParameters,
) -> str:
    """Render canonical parameters as a standard LLaMA Factory YAML document.

    将规范参数渲染为标准 LLaMA Factory YAML 文档。
    """

    document: dict[str, Any] = {
        "num_train_epochs": parameters.epochs,
        "per_device_train_batch_size": parameters.per_device_batch_size,
        "gradient_accumulation_steps": parameters.gradient_accumulation_steps,
        "learning_rate": parameters.learning_rate,
        "cutoff_len": parameters.max_sequence_length,
        "lora_rank": parameters.lora_rank,
        "lora_alpha": parameters.lora_alpha,
        "lora_dropout": parameters.lora_dropout,
        "template": parameters.template,
    }
    if model_name_or_path:
        document["model_name_or_path"] = model_name_or_path
    if dataset:
        document["dataset"] = dataset
    if parameters.max_steps is not None:
        document["max_steps"] = parameters.max_steps
    body = yaml.safe_dump(document, sort_keys=True, allow_unicode=True)
    return "# Generated by Cyrene Yield; fields map one-to-one to the training draft.\n" + body


def _optional_text(value: Any, field: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise LlamaFactoryYamlError(
            "YIELD_LLAMA_FACTORY_INVALID_VALUE", f"{field} must be non-empty text"
        )
    return value.strip()


def _validation_detail(exc: ValidationError) -> str:
    issues = []
    for error in exc.errors():
        location = ".".join(str(part) for part in error.get("loc", ()))
        issues.append(f"{location or 'value'}: {error.get('msg', 'invalid')}")
    return "; ".join(issues) or "one or more values are outside the admitted range"


__all__ = [
    "ALLOWED_FIELDS",
    "LlamaFactoryYamlError",
    "parse_llama_factory_yaml",
    "render_llama_factory_yaml",
]
